language: ruby
cache: bundler
sudo: true
services:
  - docker
before_install:
  - gem install bundler
  - 'if [[ "$DB" =~ "mysql" ]] ; then sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"; fi'
  - 'if [[ "$DB" =~ "mysql" ]] ; then sudo docker run -d -p 3306:3306 mysql:5.7; fi'
before_script: bundle exec rake db:create db:migrate
script: bundle exec rake

gemfile:
  - Gemfile
  - gemfiles/Gemfile.activemodel-serializers-xml.rb
  - gemfiles/Gemfile.rails-4.2.rb

rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1
  - 2.0.0
  - rbx
  - jruby-9.1.2.0

env:
  - DB=sqlite3
  - DB=postgres
  - DB=mysql

matrix:
  allow_failures:
    - rvm: rbx
      gemfile: Gemfile
    - rvm: rbx
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml.rb
    - rvm: rbx
      gemfile: gemfiles/Gemfile.rails-4.2.rb
    - rvm: jruby-9.1.2.0
      gemfile: Gemfile
    - rvm: jruby-9.1.2.0
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml.rb

  exclude:
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml.rb
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.activemodel-serializers-xml.rb

notifications:
  webhooks:
    - https://webhooks.gitter.im/e/40dc875af26f64f39090
